### ISSUE TITLE
Possibility of preprinting the TIGA manuscript?

### ISSUE THREAD

**Issue by dhimmel** [unmtransinfo/tiga-gwas-explorer#1]
Greetings TIGA team, some whom I know and some whom I don't.

I was recently invited to review the "TIGA: Target Illumination GWAS Analytics" manuscript. I am very interested in this project, since I think there is an unmet need to combine signals across GWAS for drug-target prioritization. I'm curious to learn more about the TIGA approach.

In addition, I appreciate the openly licensed [codebase on GitHub](https://github.com/unmtransinfo/tiga-gwas-explorer) and [corresponding webapp](https://unmtid-shinyapps.net/shiny/tiga/).

Therefore, I'd like to review the manuscript. Would it be possible to post the manuscript as a preprint? I prefer reviewing preprinted manuscripts because:

1. I can share my review immediately, and regardless of the outcome of the review process.
2. It guarantees a version of the manuscript will be available sans paywall.

Thanks for considering this request as I decide whether to accept the review invitation.

**Comment by jeremyjyang** [comment]
Greetings @dhimmel,

We had intended to post a preprint and have today submitted to bioRxiv, now pending approval.

Thanks for the interest. We are quite encouraged at the potential of this effort.

**Comment by dhimmel** [comment]
Fantastic news! Drop a link here when it's released.

**Comment by dhimmel** [comment]
Just saw that version 1 was released on bioRxiv:

- https://www.biorxiv.org/content/10.1101/2020.11.11.378596v1
- https://doi.org/10.1101/2020.11.11.378596 (does not resolve yet, always annoying that bioRxiv DOIs don't resolve immediately)

**Comment by dhimmel** [comment]
Finished my review, which is available at https://gist.github.com/dhimmel/98b7632523713b75515676870d8f3945.
